### ISSUE TITLE
Worm Gears

### ISSUE THREAD

**Issue by hamish2014** [looooo/freecad.gears#1]
Hi,

Firstly I want to thank you for the gear workbench which I have been finding very useful.

My issue has to do with trying to create a worm gear.
For which I get funny edges
![worm_issue](https://cloud.githubusercontent.com/assets/7496850/8632907/033b5f12-27b0-11e5-85f2-3909514de833.png)

Allouth not catastrophic, these edges make 3D printing the worm gear rather messy.

**Comment by looooo** [comment]
I guess a involute gear shouldn't be the base tooth geometry for a worm gear. I guess the profile is more like a rack:  
![](https://khkgears.net/new/images/worm_gear/Central-Cross-Section-of-Dual-Lead-Worm-Gear.jpg)

**Comment by looooo** [comment]
Here is a better image:
![](https://www.engineersedge.com/gears/images/power-screw.gif)

**Comment by looooo** [comment]
for sure, but someone has to do the work. This is an example of the profile which we need for the helical extrusion. It's basically a helical projection on the side face of the rack. As you can see it looks symmetric and so only two parts of a circle and one bspline are necessary to create the basic profile:
![Bildschirmfoto von 2019-09-24 14-40-45](https://user-images.githubusercontent.com/5084704/65512573-c66fdc80-ded9-11e9-95dc-d7cb37e9651a.png)

I used a rack to create the worm gear and afterwards split the rack with a box to obtain the profile. Here is the file:
[worm-gear.zip](https://github.com/looooo/freecad.gears/files/3647222/worm-gear.zip)

simple replace the ending of the file to "FCStd" to open it in FreeCAD.

**Comment by Foadsf** [comment]
> but someone has to do the work

If you had Patreon, Flattr or Liberapay, I would support you and advertise as I have done for others [here](https://www.reddit.com/r/opensource/comments/ckkl5e/supporting_free_libre_and_open_source_cad/?utm_source=share&utm_medium=web2x).

**Comment by looooo** [comment]
Feel free to test:
https://github.com/looooo/freecad.gears/commit/edc1d9a1711b89ad3abb5aa4b49feaa395b6e449
![Bildschirmfoto von 2019-09-25 23-51-26](https://user-images.githubusercontent.com/5084704/65642527-c530d380-dfef-11e9-92ef-7f94e3d2b728.png)

**Comment by looooo** [comment]
> If you had Patreon, Flattr or Liberapay, I would support you and advertise as I have done for others here.

Feel free to support me ; )
https://github.com/looooo/freecad.gears#a-gear-module-for-freecad

**Comment by Foadsf** [comment]
@looooo added you to [the list](https://www.reddit.com/r/opensource/comments/ckkl5e/supporting_free_libre_and_open_source_cad/?utm_source=share&utm_medium=web2x) and will advertise for you on Twitter. Though IMHO it would be nice to share your actual name and identity so people who are they contributing to. 
I also updated the workbench through FC Addon manager to test the new `worm_gear`, but nothing was added to the icons as far as I can see.

**Comment by looooo** [comment]
Thanks for the feedback. I have added some personal content.
> I also updated the workbench through FC Addon manager to test the new worm_gear, but nothing was added to the icons as far as I can see.

I am working on a develop branch. So if you use the addonmanager with git, simple change to the .FreeCAD/Mod/FCGear directory and switch the branch:
`git fetch --all && git checkout develop`

**Comment by Foadsf** [comment]
@looooo This seems like a nice feature to ask. inside the addon manager, one can select the branch, release and even commits. 🧐

**Comment by sgrogan** [comment]
I think something like this, from FreeCAD python console, should work?
```
import git
repo = git.Repo(FreeCAD.getUserAppDataDir()+'/Mod/FCGear')
repo.git.pull('origin','develop')
repo.git.checkout('develop')
```
unfortunately, a FreeCAD restart is required.

**Comment by Symbian9** [comment]
FTR, latest [*SolveSpace*](https://github.com/solvespace/solvespace) nightly builds got «Helix» feature, but it still not perfect and there is discussion on its forum:

- http://solvespace.com/forum.pl?action=viewthread&parent=2831

On this discussion linked «Thread for Screw Tutorial» on *FreeCAD* wiki:

- https://www.freecadweb.org/wiki/Thread_for_Screw_Tutorial

**Comment by looooo** [comment]
btw.: The worm gear is based on the idea of @mwganson: https://github.com/mwganson/ThreadProfile But instead of using only one bspline multiple curves are used.
