### ISSUE TITLE
fcgear installation fails on FreeCAD 0.20 on Mac

### ISSUE THREAD

**Issue by ryanthara** [looooo/freecad.gears#103]
fcgear workbench can't be installed on FreeCAD 0.20 on Mac. The installation works well on a FreeCAD 0.19.3 version.

See [this thread](https://forum.freecadweb.org/viewtopic.php?f=4&t=66553) in the FreeCAD-Forum.

**Comment by chennes** [comment]
This isn't really a problem with fcgear -- GitHub is sending some unexpected header information to the Addon Manager when the Addon is installed via Zip download.

**Comment by ryanthara** [comment]
> This isn't really a problem with fcgear -- GitHub is sending some unexpected header information to the Addon Manager when the Addon is installed via Zip download.

Should I close this issue?
