### ISSUE TITLE
Kerf

### ISSUE THREAD

**Issue by skintigh** [looooo/freecad.gears#105]
When adjusting for the kerf on a laser cutter, should I used "shift?" 

I don't see "kerf" mentioned anywhere in the repo, and google finds a post saying "backlash" is for laser kerf adjustment, which seems incorrect.

I'm not sure if "shift" is a typical term for MEs but perhaps for the rest of us you could label it "kerf" instead/also, as googling "gear shift" isn't going to help us newbs figure it out.

**Comment by looooo** [comment]
I have no idea what "kerf" is. Can you explain?

**Comment by skintigh** [comment]
It's the width of a cut. Say a saw blade has teeth that are 1/8" wide, so any board you cut will lose a vertical, 1/8", rectangular slice of material to sawdust. And it's trivial to account for, you just cut with one side of the blade on your line -- when you cut an 8' board at 4' you get a 4' board and a 3' 7/8" board.

With a laser cutter, kerf is the width of the laser beam... sorta. The laser is conical instead of vertical, so kerf changes with material thickness and with how well you focused the laser. And every material reacts differently in how it heats/expands/vaporizes/shrinks and thus has a different kerf on the same laser cutter. When cutting acrylic, kerf will change with thickness of the material, with the color, (and seems to change if you peel the paper off first or not), and can even be different for different batches of the same material thickness and color.

Using the above example with an 1/8" kerf diameter, if you cut an 8' board at 4' you get 2 boards that are both 3' 15/16" long. If you cut out a 1" square you get a 7/8" square. If you cut a 1" hole, you get a 1-1/8" hole. You have to account for the radius of the kerf (half kerf) on each side of each path.

Most software does not account for it at all, which might be okay when cutting large boxes but not when cutting small gears. So you have to manually add an "offset path effect" to every cut with a different offset for every material, color, etc. And then invariably you have to change most/all of them when you bring your design to the shop and cut it. Eventually you get a design that cuts perfectly, then a few days later you cut it again and parts no longer fit correctly, so you have to re-adjust paths one by one. I need to cut 30-50 gears in 6 or 7 different colors for one design...

What I'm saying is kerf is a pain in the butt and constantly changing, so if "shift" can account for kerf that would be AMAZING, I could just change some parameters in the design or script file and have it recompute every cut. Shift seems to add an offset to the path in every direction, but I haven't carefully measured it's effect on tooth width.

**Comment by looooo** [comment]
shift is definetly not the same as kerf. shift is used to create gears for a given axial distance and give number of teeth. I guess what you want is a offset tool as it is available in the part-workebnch.

**Comment by skintigh** [comment]
3D part offset is broken for gears, as are most things it seems, but 2D part offset works, thanks!

But now you've piqued my interest with shift... so I can keep the module and z the same but still adjust the size of the gear...?!? Do both gears have to be shifted to mesh well? Does this hurt efficiency? 

This could be exactly what I need for the last bit of my design -- I need a lot of idle gears of different sizes and modules, but would prefer they were all on the same 1 or 2 axles and not 6-12 more axles. If you have any links I can read more about this, that would be super helpful!

Thanks again!

**Comment by looooo** [comment]
Look here for example: https://www.tec-science.com/mechanical-power-transmission/involute-gear/profile-shift/

**Comment by skintigh** [comment]
Thank you!
