### ISSUE TITLE
Wrong Transverse_pitch calculation on involute rack

### ISSUE THREAD

**Issue by schwantz69** [looooo/freecad.gears#113]
Hi,
The involute rack have a problem on the transverse_pitch calulation, for example:
Module 3 rack with 10° helix angle calculate 9,428mm but should be 9,5701
Can you fix it ?
Thank you !

p.s. change the properties_from_tool have no effects for me

**Comment by looooo** [comment]
I guess properties_from_tool should have an influence, but I have to think about it :)

**Comment by schwantz69** [comment]
I have read another user have open in the past the same topic and he have solved it changing the properties_from_tool in False but for me nothing change.. Is possible that my version is obslolete ? Or the installation of the package are not correct ?
It's a big problem for me.
Thank you for your work

**Comment by schwantz69** [comment]
As alternative for solve the problem there is the possibility to re install the previous version of FCgear ? If yes where I can download the zip file ?
Thank you

**Comment by looooo** [comment]
There were some issues introduced. I currently don't have the capabilities to fix them.

**Comment by schwantz69** [comment]
Thank you for your answer, so please can you send me the instruction for install the older version that was without bug ?

**Comment by schwantz69** [comment]
> There were some issues introduced. I currently don't have the capabilities to fix them.

I can understand but please can you tell me where I can found the previous version of Fcgear and how I can install it ?
For me the previous version was ok and I will re install it.

Thank you in advance

**Comment by looooo** [comment]
you can use branch `2022` which works for me.

**Comment by looooo** [comment]
this should be fixed with https://github.com/looooo/freecad.gears/commit/29e45aa613e0ea0cd6952597f5bbf49dd99270ca

**Comment by schwantz69** [comment]
I can confirm that now work correctly !
Many thanks for your great work.
