### ISSUE TITLE
Create a helical involute gear on an existing shaft

### ISSUE THREAD

**Issue by maxwxyz** [looooo/freecad.gears#121]
Not sure if it is possible (otherwise maybe a feature request):
I am trying to create a helical involute gear on an existing hollow shaft (see: [FreeCAD forum](https://forum.freecadweb.org/viewtopic.php?f=3&t=75255))

Is this possible with the Gears-WB, especially with the "chamfer" or phase out of the teeth into the existing shaft? Is it also possible to create an inner stub shaft spline with Gears-WB on an existing hollow shaft?

**Comment by looooo** [comment]
not really. I tried to create something similar with the part-wb and gear-wb, but I guess this is not what you want:
<img width="591" alt="Bildschirm­foto 2023-01-15 um 11 47 13" src="https://user-images.githubusercontent.com/5084704/212536415-7c0317ad-52e6-402b-94c8-b2aeb3315acf.png">

**Comment by maxwxyz** [comment]
not bad, would you share the file or tell me how you did it?

**Comment by luzpaz** [comment]
This ticket can be closed.
