### ISSUE TITLE
Unable to install FCGear in FreeCAD v0.19

### ISSUE THREAD

**Issue by amanbop** [looooo/freecad.gears#124]
# In Windows 10, FreeCAD V0.19 :

1. This package is not coming up in Addon Manager External Workbenches list of packages available to install....

2. I tried to install using pip in Windows 10, the folders shown in the attached image got created in site packages.. but the workbench did not show up in the FreeCAD upon start...

3. I removed and installed them to the user/roaming/freecad/mod folder where all the other external workbenches are installed. Again the same folders got created with python code in them but still it did not show up in FreeCAD upon start...

What is the correct way to install it in Windows10, FreeCAD V0.19?

![image](https://user-images.githubusercontent.com/6539112/227142119-96bfaf16-c6a0-472b-9d98-ff2e1e68a667.png)

**Comment by luzpaz** [comment]
Is this still relevant ?

**Comment by luzpaz** [comment]
@looooo close please
