### ISSUE TITLE
cycloide gears: additional parameter (head, fillets), + check geometry

### ISSUE THREAD

**Issue by looooo** [looooo/freecad.gears#15]
There are not that many documents about cyloide gears, and I am not quite sure if the geometry is right.

- [x] head parameter
- [ ] head fillet
- [ ] foot fillet

**Comment by iplayfast** [comment]
No it's not right.
This source (found online from http://www.zincland.com/hypocycloid should give you a leg up ) 
 [hypocycloid.zip](https://github.com/looooo/freecad.gears/files/3589086/hypocycloid.zip)
also check https://github.com/dsuarezv/GearSolver

**Comment by looooo** [comment]
@iplayfast the cycloid gear in freecad.gears is another type which can be found here:
https://en.wikipedia.org/wiki/Cycloid_gear

head and root fillet were added so I close this issue.
