### ISSUE TITLE
Generated strange worm gear when the height of the gear is greater than 450mm (425mm)

### ISSUE THREAD

**Issue by StartEndUser** [looooo/freecad.gears#162]
![shot1](https://github.com/looooo/freecad.gears/assets/96003651/e6a302a3-dab6-452d-8517-5f96458328c4)
*(Left: height=400mm Right: height=500mm)*

After generating a worm gear I changed the height to 500mm and it generates a strange stuff.

![shot2](https://github.com/looooo/freecad.gears/assets/96003651/c530b969-fd19-4711-90fc-bf3f3b0c5dcf)
*(height=425mm)*
Things started to get weird when the height was about 425mm.
But not so obvious.

![shot3](https://github.com/looooo/freecad.gears/assets/96003651/67203951-c867-429b-9ebc-b467f575323d)
*(height=450mm)*
When the height was 450mm. I received an error.

The error was:
```
21:36:05  Traceback (most recent call last):
  File "/home/SEU/.local/share/FreeCAD/Mod/freecad.gears/./freecad/gears/basegear.py", line 127, in execute
    gear_shape = self.generate_gear_shape(fp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/SEU/.local/share/FreeCAD/Mod/freecad.gears/./freecad/gears/wormgear.py", line 184, in generate_gear_shape
    shape = helical_extrusion(part.Face(full_wire), h, h * np.tan(beta) * 2 / d)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/SEU/.local/share/FreeCAD/Mod/freecad.gears/./freecad/gears/basegear.py", line 215, in helical_extrusion
    pipe_shell, top_wire = make_pipe(spine, wire)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/SEU/.local/share/FreeCAD/Mod/freecad.gears/./freecad/gears/basegear.py", line 210, in make_pipe
    return (mkPS.shape(), mkPS.lastShape())
            ^^^^^^^^^^^^
<class 'Part.OCCError'>: BRep_API: command not done
21:36:05  Recompute failed!
```

![shot4](https://github.com/looooo/freecad.gears/assets/96003651/962e0cd3-41f5-47e2-853c-04bad74c6c9a)
*(height=455mm)*
If the height is greater than 450mm. I get the strange worm gear again.

I'm using:
- FreeCAD 0.21.2 Revision: 33771 (Git)
- freecad.gears the latest version (I've already updated it to the latest version and it still has the problem)

**Comment by looooo** [comment]
Hmm, I think this is an issue with the geometry library (occt).
