### ISSUE TITLE
Crown gear creates cylinder with no gears

### ISSUE THREAD

**Issue by j-m-patterson** [looooo/freecad.gears#191]
FreeCAD version 0.21.2
freecad.gears version 1.3.0

When I attempt to create a crown gear, it creates the crown, but with no gears, just a tube. I've tried fiddling with the parameters of the gear, but nothing I do seems to create gears.

![FCAD crown gear](https://github.com/user-attachments/assets/1d214223-a846-4351-8f5d-d6062c963c4d)

**Comment by looooo** [comment]
just toggle preview mode (in the properties panel)
