### ISSUE TITLE
Axle hole will not go all the way through depending on beta angle

### ISSUE THREAD

**Issue by dogunter** [looooo/freecad.gears#196]
I am using FreeCAD 1.0 with the geers workbench 1.3.0.

If I create a simple involute gear and keep all the settings at the defaul, then set axel_hole as true, I get the expected result. However, if I then set a beta angle value of 12º or higher, the bottom surface of the hole turns solid, the hole no longer cuts all the way through.

The beta value of 12º or more which demonstrates this varies depending on the overall size of the gear one needs, but it works to demonstrate the behavior I'm running into.

The workaround is to simply leave axle_hole set to false and create a pocket hole in the parts design workbench.

**Comment by loughkb** [comment]
I can verify this behavior.  Beta angle results in the hole not going all the way through.   Came here to report it, but found this, so I thought I'd just add my observation as well.   Wonderful workbench by the way!  You guys have done an excellent job on it.  Very useful.  Thanks to all the devs.

**Comment by looooo** [comment]
this is a result of a occt-issue. See this failing test:
https://github.com/looooo/freecad.gears/blob/master/tests/tests.py#L10
