### ISSUE TITLE
Larger tooth count on involute gears causes loss of detail on teeth?

### ISSUE THREAD

**Issue by waterlubber** [looooo/freecad.gears#23]
I'm trying to set up a couple simple involute gears, but for whatever reason on high "tooth" counts the model drops to a lower accuracy:
![image](https://user-images.githubusercontent.com/7517025/49192129-b766df00-f347-11e8-9d98-36cfad67e0fb.png)

FreeCAD details:
`OS: Linux Mint 18.3 Sylvia
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15263 (Git)
Build type: Release
Branch: master
Hash: 7ceac311b3c5dc1b89e85b15b310ddd1d1673561
Python version: 2.7.12
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
`

Smaller gears, around 30 teeth, work fine. What gives?

**Comment by looooo** [comment]
What do you mean with "lower accuracy"?

**Comment by looooo** [comment]
A gear with many teeth has similar tooth-shape as a rack. So this is not a low accuracy.
