### ISSUE TITLE
Rack wrong dedendum

### ISSUE THREAD

**Issue by schwantz69** [looooo/freecad.gears#34]
Hi,
I'm new here (and in FreeCAD too :-) ). I'm using FCGear because I need to create a Rack. 
I have test FCGear but I found a problem:
In my sample I have try to creatre a rack 24x24 Module 2 but after I have create it I found that the teeth are wrong in fact the teeth addendum and the teeth dedendum are always equal (in my example was alway 2 but the correct is Addendum = 2 and dedendum = 2,5).
How I can solve this important topic ?
Can you please add the possibility to indicate this two paramenters ? It could be useful also in case of teeth modification.
Thank you for your precious work !

**Comment by looooo** [comment]
I guess we should add a `clearence` parameter. But for now I simple added your suggestion:
https://github.com/looooo/freecad.gears/commit/b2d8fa7fbf036da3df5fe3eee459cad3d01d1690

To add the parameter I would like to find a good way to keep backward compatibility first. So let's keep this issue open.

![](https://www.sdp-si.com/resources/elements-of-metric-gear-technology/images/Fig1-2.jpg)

**Comment by schwantz69** [comment]
Dear Lorenz,
Thank you very much for your fast reply !
I see your modification in py module but... how I can use it ? I'm sorry
but I'm new on FreeCAD and I guess the py module modification is for
advanced user ! 😀
So please can you send me detailed instructions ?
Thank you very much, your help is precious for me.

p.s. many compliments for your work !

Il giorno lun 3 feb 2020 alle ore 09:53 lorenz <notifications@github.com>
ha scritto:

**Comment by looooo** [comment]
> how I can use it ?

Assuming you installed freecad.gears (FCGears) with the addon-manager, you can update the latest changes with the same tool. https://www.freecadweb.org/wiki/Std_AddonMgr

**Comment by schwantz69** [comment]
Oh, sorry.... 
Ok I have test it but unfortunately I'm was not clear and I'm very sorry.
As you for sure know there is different type of teeth profile under DIN 3962 - 3967 normative.
The most used is accordin DIN 3962 Profile II, this normative define also the position of the pitch line in the teeth height where:
Addendum = Normal module
Dedendum (module + cleareance) = Normal module * 1,25
so it mean that for easely calculate the total teeth deep is sufficient moltiply the normal module x 2,25 in fact:
Module 2 = 2*2,25 = 4,5mm = (2 + (2*1,25))
Module 3 = 3*2,25 = 6,75mm = (3 + (3*1,25))
.......

Could you please modify your script with the described formula ? Thank you !
And excuse me another time if in my previous post I'm was not clear.

**Comment by looooo** [comment]
> As you for sure know there is different type of teeth profile under DIN 3962 - 3967 normative.

Do you have a drawing? I do not really understand what is not correct with the recent changes.
With the addition of the clearence the total tooth-height can be calculated like this:
`hight = ((1 + clearence) + (1 + head)) x module`
So for head = 0, clearence = 0.25 and module = 2 you will get a total height of  `2 x ((1 + 0.25) + (1 + 0) = 4,5`. Isn't that correct?

![Bildschirmfoto von 2020-02-03 22-44-58](https://user-images.githubusercontent.com/5084704/73693595-ccbb6400-46d6-11ea-90f3-6bb22f441113.png)

**Comment by schwantz69** [comment]
Dear Lorenz, 
You are right ! Probably something was wrong during the update because this morning I have try to replicate the problem but is correct ! I'm very sorry.
Unfortunately I have another issue.....
I have built a rack 29x29 Module 3 helical teeth 20° (see the attachment), as for checking the teeth I use a roller Diam. 6mm and the roller size should be 31,297 but is 31,222.
I have check and the problem is the pressure angle that should be 20° but in realty is 21,1728°.
I have made a mistake ?
Thank you for your help
![Annotazione 2020-02-04 080213](https://user-images.githubusercontent.com/7071090/73722318-80981000-4726-11ea-867d-57bed4826386.png)
![Annotazione 2020-02-04 080358](https://user-images.githubusercontent.com/7071090/73722325-83930080-4726-11ea-9a40-f21f7b87c6ca.png)

**Comment by looooo** [comment]
The gear-properties are internally recomputed to match a rotated tool with the user-given properties. So module and alpha are recomputed.
I added a property (tool_properties) which you can set to `False`:
![Bildschirmfoto von 2020-02-04 10-44-49](https://user-images.githubusercontent.com/5084704/73733044-877d4d80-473b-11ea-8ac7-cdd6bfac9594.png)

The same is now possible with the involute-gear:
https://github.com/looooo/freecad.gears/commit/397c10fdf23081342c651319523ba88210c7b238

Hopefully this solves your issue.

**Comment by schwantz69** [comment]
Dear Lorenz,
Unfortunately no... take a look below
Thank you
![Annotazione 2020-02-04 110731](https://user-images.githubusercontent.com/7071090/73734939-bf39c480-473e-11ea-807e-4331b188096e.png)
![Annotazione 2020-02-04 110812](https://user-images.githubusercontent.com/7071090/73734951-c234b500-473e-11ea-8446-cd162f7b25ed.png)

**Comment by looooo** [comment]
How is he angle measured?

**Comment by looooo** [comment]
Ah I see now the problem. There is indeed something wrong with the internal computation of alpha.

**Comment by schwantz69** [comment]
> 
> 
> How is the angle measured?
> Is the sketch placed on the fron-face of the gear or are you cutting the gear by a plane rotated by beta?

Rotated plane

**Comment by schwantz69** [comment]
> 
> 
> Ah I see now the problem. There is indeed something wrong with the internal computation of alpha.

Great !

**Comment by looooo** [comment]
ok, it should be fixed. Please try again.

**Comment by schwantz69** [comment]
Dear Lorenz,
I'm sorry no.... 
![Annotazione 2020-02-04 142405](https://user-images.githubusercontent.com/7071090/73748636-231db680-475a-11ea-8d37-4b334def7333.png)

**Comment by looooo** [comment]
ah sry, you need to enable properties_from_tool again.

![Bildschirmfoto von 2020-02-04 14-42-30](https://user-images.githubusercontent.com/5084704/73749930-97595980-475c-11ea-88b6-1223914a7f97.png)

**Comment by schwantz69** [comment]
Perfect ! Now work very well.
Thank you very much for your help !
