### ISSUE TITLE
Rack Lenght

### ISSUE THREAD

**Issue by schwantz69** [looooo/freecad.gears#35]
Dear Lorenz,
Unfortunately I have found another small issue that I hope is very easy for you to solve.
The issue is regarding the total lenght of the rack, on the attached pictures you can see I have defined a rack 29x29 Module 3 with 100 teeth helical teeth 19,528333 Deg. Angle that mean a transversal Module 3,18310 that correspond to pitch 10,0000mm
With the mentioned data the theorical lenght of the result rack it will be 1000mm (we assume that both heads start exactly with half teeth gap).
Unfortunately the result lenght of the rack is 997,898mm, it seems because the rack do not start end end in the middle of teeth gap.
Do you think there is the possibility to solve this issue easely ?
Thank You !
![Annotazione 2020-02-05 082630](https://user-images.githubusercontent.com/7071090/73820852-f49fea00-47f2-11ea-8e1f-3095193105c2.png)
![Annotazione 2020-02-05 082720](https://user-images.githubusercontent.com/7071090/73820856-f7024400-47f2-11ea-855c-f6eb130de0a6.png)

**Comment by looooo** [comment]
can't reproduce:
![Bildschirmfoto von 2020-02-05 10-05-10](https://user-images.githubusercontent.com/5084704/73827013-14d5a600-47ff-11ea-99b1-b71cc090b445.png)

To get 100 x pitch you need to create 101 teeth and measure at the same points of the profile. (see my attached picture)

**Comment by schwantz69** [comment]
Dear Lorenz,
Unfortunately no, all the racks are measured like my DWG.
For example look at the attached document pick from a catalogue of a famous German producer.
![Annotazione 2020-02-05 082630](https://user-images.githubusercontent.com/7071090/73829987-2cfbf400-4804-11ea-9dbe-67412a93f00c.png)
![Annotazione 2020-02-05 104016](https://user-images.githubusercontent.com/7071090/73829994-2f5e4e00-4804-11ea-84ac-9ea1bb895b64.png)

**Comment by looooo** [comment]
Ok, making the ending like described in your drawing make sense. I changed that:
https://github.com/looooo/freecad.gears/commit/95f6de16fb27148074163d9b4c7bb3ab8d116ee7

**Comment by schwantz69** [comment]
Dear Lorenz,
Thank you ! I have tested and it is ok.
If you have in plan to visit Italy tell me, it would be a pleasure to meet you and of course drink a beer together !
