### ISSUE TITLE
2D gears

### ISSUE THREAD

**Issue by cfernandesINEGI** [looooo/freecad.gears#38]
Is it possible to get a 2D gear with no face width? I want to mesh it in my python IDE...

Best regards
Carlos

**Comment by looooo** [comment]
I added a module for this porpose:

```
import matplotlib.pyplot as plt
from pygears import profile
p = profile.InvoluteProfile(m=1, z=15)
plt.plot(*p.profile().T)
plt.show()
```

**Comment by cfernandesINEGI** [comment]
It is perfect. Thank you.

Best regards,
Carlos Fernandes
