### ISSUE TITLE
switch license: gpl-3

### ISSUE THREAD

**Issue by looooo** [looooo/freecad.gears#44]
@luzpaz @kcleung I would like to move to gpl3. As you contributed to this library, I would like to know if this is fine for you.

**Comment by kcleung** [comment]
Hey looooo

Apart from a standalone plugin, the freecad.gear backend can also be used as a library for some other applications.

obviously, the intention is that any derivative of freecad.gear must also be open source.  However, if it is licensed to the vanilla GPL, (such as v 3), then other software / plugin that merely calls the function of freecad.gear must also be GPL then This will hamper the use of freecad.gear

So perhaps the lesser GPL (LGPL) 3 will be more appropriate.  This will enable other software or plugins with other licenses (such as proprietary) that merely call the function of freecad.gear, but does not use or incorporate any freecad.gear code, to call functions of freecad.gear

**Comment by looooo** [comment]
@kcleung i would like toll avoid lgpl. Because using lgpl allows anyone to fork the module and offer a commercial alternitive instead of contributing.

**Comment by looooo** [comment]
@kcleung gpl3 vs gpl2 is not a big deal. Please give your ok, so we can move on.

**Comment by kcleung** [comment]
> 
> 
> @kcleung gpl3 vs gpl2 is not a big deal. Please give your ok, so we can move on.

I give consent to switch to GPL3

**Comment by looooo** [comment]
thx
