### ISSUE TITLE
[SOLVED] Impossible to install/access to FCGear Workbench

### ISSUE THREAD

**Issue by Banane84** [looooo/freecad.gears#45]
Hello I'm using FreeCad 0.18~pre1+dfsg1-5
FreeCAD 0.18, Libs: 0.18R
On debian 10

I install FCGear workbench from addon manager. 
After restarting FreeCad no Gears workbench apears ;(

I cheched in~/.freecad/Mod I've a directory FCGears full
No error message at startup
in log grep FCGear I found
`Log: Init:      Initializing /home/x/.FreeCAD/Mod/FCGear(Init.py not found)... ignore
Log:    /home/x/.FreeCAD/Mod/FCGear
Log: Init:      Initializing /home/x/.FreeCAD/Mod/FCGear(InitGui.py not found)... ignore
`
I feel install just did'nt work properly

**Comment by looooo** [comment]
Best to use the py2 branch for 0.18. most likely the wb is hidden by a freecad/__init__.py file. There should exist only one such file.
The py2 branch is old-style and should work out of the box with freecad 0.18.

**Comment by Banane84** [comment]
Thanks it worked directly
