### ISSUE TITLE
Problem with module in helical rack

### ISSUE THREAD

**Issue by LeeKC0001** [looooo/freecad.gears#46]
I am completely new to FreeCAD and other CAD. In a project to re-create a helical rack by 3D printing, I measured the distance between 3 teeth of a rack and get a value of 4 mm.

So I calculate the module by this formula (4 mm / 3 / pi).

However, the distance between 3 teeth generated by FCgear workbench is 4.26 mm.

![image](https://user-images.githubusercontent.com/65098350/81488740-59aa2680-929f-11ea-9be8-91501b58fc07.png)

I noticed that the distance between 3 teeth is 4 mm in a spur rack (beta set to 0).

![image](https://user-images.githubusercontent.com/65098350/81488768-fe2c6880-929f-11ea-990d-f08ee7e2eb36.png)

Did I missed out something?

Your help is much appreciated.

Best regards.

KC

**Comment by looooo** [comment]
You can switch properties_from_tool to false. Then the input module is used as the traverse module. I guess this is what you want.

**Comment by LeeKC0001** [comment]
I see. Thanks a lot for clearing up my misconception!
