### ISSUE TITLE
Freecad 0.18 FC gear installed App but no icon in the work bench

### ISSUE THREAD

**Issue by Munter-one** [looooo/freecad.gears#47]
Hello 
is there somwhere to help me ? I work with an old computer ( 32 bit sony) .
there is win 10 running with freecad 018 build 4( Git  Tag)

lots of Add ons are working ( assembly 4 / 2 ,A2Plus)
if i install FCGear  my machine tells me i installed sucsesfully but i do not have any Icon in my workbench

**Comment by looooo** [comment]
please install the py2-branch manually if master makes problems:
https://github.com/looooo/freecad.gears/archive/py2.zip

**Comment by Munter-one** [comment]
Hello Lorenz 
Thank you too much for helping me  it works fantastic
