### ISSUE TITLE
Bevel gears wrong angle?

### ISSUE THREAD

**Issue by Schildkroet** [looooo/freecad.gears#49]
Hello,
i was playing around with Gear-WB and it seems that the angle of bevel gears is incorrect. I created to identical bevel gears with following params:
![image](https://user-images.githubusercontent.com/29074960/87192752-6ecf2000-c2f7-11ea-82a5-29cd0749b355.png)

If i place them together with 90° degree, the angle of the teeth is not matching:
![image](https://user-images.githubusercontent.com/29074960/87192813-90300c00-c2f7-11ea-8f82-3d69d10e1ae3.png)

**Comment by looooo** [comment]
please set "reset_origin" to false and do not add linear translation (only angle).

**Comment by looooo** [comment]
btw. the faces of the tooth-heads should not be parallel. The gears are not correctly placed.
