### ISSUE TITLE
Crown gear not working

### ISSUE THREAD

**Issue by Daniux03** [looooo/freecad.gears#54]
Hi, I've generated a crown gear using the FCgear add-on but the pieces that need to cut the main ring don't do it.
I'm running on windows 10 and the latest stable Freecad version as of 9/12/2020.
![Screenshot (10)](https://user-images.githubusercontent.com/71188495/93001358-b5770b80-f52e-11ea-93a1-a45aa06af671.png)

**Comment by Daniux03** [comment]
I have just understood how it maybe should've been used. You generate the gear then you break it in solids using the draft the you fuse all the cutting pieces and finally you cut the ring with all the piec s.

**Comment by looooo** [comment]
simple switch the construction property.
