### ISSUE TITLE
Undercut option creates artifacts w/ high teeth count and high numpoint precision

### ISSUE THREAD

**Issue by herrgerd** [looooo/freecad.gears#55]
Creating a 150 teeth module 2 involute gear showed strange errors when I imported the STEP file into other CAD systems.
On further inspection I saw strange "spikes" in the model:

![zoomout](https://user-images.githubusercontent.com/24494466/94362357-fccad380-00ba-11eb-9d01-2156f8ddb14a.JPG)
![zoomin](https://user-images.githubusercontent.com/24494466/94362356-fb99a680-00ba-11eb-809b-abde77846af2.JPG)

They only occur when using high numpoint precision (above 10) and high teeth count. Those are not **sane** settings someone would use. Just wanted to let you know!

**Comment by looooo** [comment]
while undercut intersection with involute can be improved, I don't think it's a big issue for high number of teeth. 
an additional root fillet is on the todo list if this is what you want.

**Comment by looooo** [comment]
Additional root fillet was added to the megagrant-branch. Please use this property and not undercut if you have a high number of teeth.
