### ISSUE TITLE
Involute gear thooth profile for use with worm gear

### ISSUE THREAD

**Issue by DickyOZ** [looooo/freecad.gears#58]
Hi, I have just downloaded this very useful gears mod. I have two issues I can't solve.
1. How do I alter the tooth profile to cater for spur gears driven by a worm drive?
2. How do calculate the distance between centres of the worm gear and spur gear for them to mesh properly?

**Comment by looooo** [comment]
If you mean by 1. something like this:
![this](https://sc02.alicdn.com/kf/HTB1D_A1bUD.BuNjt_h7q6yNDVXaL.jpg)
such gears are not yet available within freecad.gears. 

2. The involute gear has a property `dw` which is the computed pitch diameter.

**Comment by DickyOZ** [comment]
Many thanks for the prompt reply it has helped a lot.
I solved the first issue by using a torus solid to cut away the involute gear to the shape shown in your reply. At least it is close enough to match the gears I'm using.
The axial distance precision is causing me a lot of grief in 3D printing - probably a limitation of the 3D accuracy.
Many thanks for you excellent Gears module it has made my life much easier
![gears](https://user-images.githubusercontent.com/63839841/97287879-d4d4b880-1890-11eb-9afe-b42143b85126.jpg)
. Incidently the latest FreeCAD (1.8) addons manager doesn't look anything like the previous version. I've programmed using many languages but have yet to dabble in python. I've attached a pic of the (exposed) gears of my home made star tracker.

**Comment by looooo** [comment]
this looks impressive. If you have some time feel free to post this in the freeecad show-case forum:
https://forum.freecadweb.org/viewforum.php?f=24

**Comment by looooo** [comment]
> Incidently the latest FreeCAD (1.8) addons manager doesn't look anything like the previous version.

I repaired the addon-manager for 0.18 versions (linux/mac). If you are ùsing one of these plattforms simple download the `rev1` file here:
https://github.com/FreeCAD/FreeCAD/releases/tag/0.18.4

Not sure if windows was updated yet.

**Comment by DickyOZ** [comment]
Thanks looooo, the WIN 64 version hasn't been updated yet. I'll keep checking.
The Star tracker uses a Nema 17 stepper to drive the gear chain. And 28PYJ-48 steppers to align and tilt to locate the celestial pole (necessary to find the CP in the southern hemisphere). The whole thing is controlled by an ESP-32 MCU which has two CPUs  and four built-in timers. I dedicate one CPU and one very accurate timer to drive the rotation stepper.  The other CPU is used for communication and control processes. The MCU reads orientation data from an MPU-92.65 sensor. It also connects to my phone via Bluetooth to give a visual indication of the setup and to control the tracker. The phone App I wrote uses GPS to lookup magnetic declination and align the tracker. The rotation is accurate to within a few seconds a day (overkill) but the compass and accelerometer leave a bit to be desired; hence the 'Nudge' buttons.
![StarTrackerBTs](https://user-images.githubusercontent.com/63839841/97298705-8f6bb780-189f-11eb-890c-88fa7a796868.JPG)
![StarTrackerBTv](https://user-images.githubusercontent.com/63839841/97298711-909ce480-189f-11eb-9141-d307ed9e6ff6.JPG)
