### ISSUE TITLE
Helical internal involute gear

### ISSUE THREAD

**Issue by ofpkubi** [looooo/freecad.gears#98]
Hi,

It seems when I give a beta other than zero (even if 0.001 degree) for an internal involute gear, it loses its proper tooth geometry and goes into a plane walled tooth.

**Reproduce**
Please see the attached file. Just change the beta in the spreadsheet.
[planetary.zip](https://github.com/looooo/freecad.gears/files/7873681/planetary.zip)

**SW version(s) used**
Debian testing
Stable: FreeCAD_0.19.3-Linux-Conda_glibc2.12-x86_64
Weekly: FreeCAD_weekly-builds-27008-Linux-Conda_glibc2.12-x86_64
Realthunder's: FreeCAD-asm3-Daily-Conda-Py3-Qt5-20220111-glibc2.12-x86_64

Development branch of freecad.gears. Installed on 2022-01-14 from github (pip install https://github.com/looooo/FCGear/archive/develop.tar.gz)

**Comment by looooo** [comment]
@ofpkubi can you post a screenshot?

**Comment by ofpkubi** [comment]
Here you are @looooo .

15, 44 and 60 teeth
left side: beta=0 degree
right side: beta=1degree

![gear issue](https://user-images.githubusercontent.com/602106/149630299-c1dc1197-27b3-4841-9d40-2807143a6a5c.png)

**Comment by looooo** [comment]
I guess this is related to the deviation parameter. Try to set it to a smaller value.

**Comment by ofpkubi** [comment]
Which one is the deviation parameter?

**Comment by looooo** [comment]
in the view tab, there is a deviation property, see the image.
you can also set it globally in setting, part-design, second tab

hope this helps.
![Bildschirmfoto von 2022-01-16 12-12-55](https://user-images.githubusercontent.com/5084704/149657561-60f7c7db-9e24-40bc-b4bc-66a58692e003.png)

**Comment by ofpkubi** [comment]
Thanks!
Now, this is interesting.
Originally the deviation is 0.2 on all objects. If I change it to 0.05 on the large gear, it shows a better tooth profile. But, if I change it back to 0.2, the toot profile stays good.
But anyway, this seems to be only a viewing issue, the exported STL looks good.

I think there is no bug then.

**Comment by looooo** [comment]
@ofpkubi if it is solved, please close this issue. thanks

**Comment by ofpkubi** [comment]
Done. Thanks a lot!
